# Generated by Django 2.2 on 2020-01-22 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='imei',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
