# Generated by Django 2.2 on 2020-01-17 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200117_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpermission',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='accounts.Permission'),
        ),
    ]
