# Generated by Django 2.2 on 2020-01-16 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='audiences',
            field=models.ManyToManyField(blank=True, related_name='news_audience', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='newsaudiences',
            name='audience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
