# Generated by Django 3.0 on 2019-12-18 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contents', '0002_auto_20191218_0417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_notifications_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='NotificationsAudiences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('read_on', models.DateTimeField(blank=True, null=True)),
                ('audience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.Notifications')),
            ],
        ),
        migrations.AddField(
            model_name='notifications',
            name='audiences',
            field=models.ManyToManyField(through='contents.NotificationsAudiences', to=settings.AUTH_USER_MODEL),
        ),
    ]
