# Generated by Django 2.2 on 2020-01-16 16:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_auto_20200116_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='audiences',
            field=models.ManyToManyField(blank=True, related_name='my_news', to=settings.AUTH_USER_MODEL),
        ),
    ]
