# Generated by Django 2.2 on 2020-01-16 00:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0003_auto_20200116_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='audiences',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
