# Generated by Django 2.2 on 2020-01-14 22:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('regulations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendanceplace',
            options={'ordering': ('-updated',)},
        ),
        migrations.AlterModelOptions(
            name='attendancerule',
            options={'ordering': ('-updated',)},
        ),
        migrations.AlterModelOptions(
            name='attendancetime',
            options={'ordering': ('-updated',)},
        ),
        migrations.AddField(
            model_name='attendanceplace',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendanceplace',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='attendancerule',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendancerule',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='attendancetime',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendancetime',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
