# Generated by Django 2.2 on 2020-01-24 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
        ('regulations', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UnAttendenceMembership',
            new_name='UnAttendanceMembership',
        ),
    ]
