# Generated by Django 2.2 on 2020-01-22 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regulations', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AttendaceEvent',
            new_name='AttendanceEvent',
        ),
        migrations.RenameField(
            model_name='attendanceevent',
            old_name='is_attendace_day',
            new_name='is_attendance_day',
        ),
    ]
