# Generated by Django 2.2 on 2020-01-28 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regulations', '0002_auto_20200124_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancemembership',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_membership', to='teachers.TeacherProfile'),
        ),
    ]
