# Generated by Django 2.2 on 2020-01-29 17:43

import apps.regulations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulations', '0004_attendancehistory_is_late_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancehistory',
            name='image',
            field=models.ImageField(upload_to=apps.regulations.models.attendance_image_path),
        ),
    ]
