# Generated by Django 2.2 on 2020-01-29 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regulations', '0005_auto_20200129_1743'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendancehistory',
            old_name='is_late_attendance',
            new_name='is_bad_attendance',
        ),
    ]
