# Generated by Django 2.2 on 2020-03-23 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulations', '0007_attendancehistory_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancehistory',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
