# Generated by Django 2.2 on 2020-04-09 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
        ('regulations', '0008_attendancehistory_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceDatePerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_checks', models.PositiveIntegerField()),
                ('checks', models.PositiveIntegerField()),
                ('late_attendances', models.PositiveIntegerField()),
                ('early_attendances', models.PositiveIntegerField()),
                ('outside_checks', models.PositiveIntegerField()),
                ('holidays', models.PositiveIntegerField()),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.TeacherProfile')),
            ],
        ),
    ]
