# Generated by Django 2.2 on 2019-12-26 21:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Teacher',
        ),
        migrations.CreateModel(
            name='TeacherImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='teachers.Teacher')),
            ],
        ),
    ]
