# Generated by Django 2.2 on 2019-12-26 22:12

import apps.teachers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_auto_20191226_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherimage',
            name='image',
            field=models.ImageField(upload_to=apps.teachers.models.image_path),
        ),
    ]
