# Generated by Django 2.2 on 2020-01-12 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_auto_20200109_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachers.Position'),
        ),
    ]
