# Generated by Django 2.2 on 2020-01-13 23:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_teacherprofile_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ('-updated',)},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ('-updated',)},
        ),
        migrations.AlterModelOptions(
            name='teacherprofile',
            options={'ordering': ('-updated',)},
        ),
        migrations.AddField(
            model_name='department',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='position',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='position',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
